#pragma once

enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_END };


enum OBJID { OBJ_PLAYER, OBJ_BULLET, OBJ_MOUSE, OBJ_MONSTER, OBJ_ITEM, OBJ_COLLIDER, OBJ_END };


enum MOBTYPE { MOB_DF, MOB_FW,MOB_CH, MOB_END };

enum ITEMTYPE { ITEM_SHIELD, ITEM_SPEED, ITEM_COIN, ITEM_BOMB, ITEM_END};

